name: AdrianUribarri
favicon: null
layout_spectrum: 0.8
title: Adrian Uribarri
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-6293149-12
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
